// Regenerates libs/react/playback/src/lib/glyphs.ts from VexFlow 4's Bravura outline data.
// Usage: npm pack vexflow@4.2.5 && tar -xzf vexflow-4.2.5.tgz && node tools/scripts/extract-glyphs.mjs package/src/fonts/bravura_glyphs.ts
import { readFileSync, writeFileSync } from 'node:fs';
const [, , file] = process.argv;
const src = readFileSync(file, 'utf8');
const font = new Function('return ' + src.slice(src.indexOf('{'), src.lastIndexOf('}') + 1))();
const want = ['gClef', 'noteheadWhole', 'noteheadHalf', 'noteheadBlack', 'augmentationDot', 'flag8thUp', 'flag16thUp', 'flag8thDown', 'flag16thDown', 'accidentalSharp', 'accidentalFlat', 'accidentalNatural'];
const toPath = (o) => {
  const t = o.trim().split(/\s+/);
  let i = 0;
  let d = '';
  const n = () => Number(t[i++]);
  while (i < t.length) {
    const c = t[i++];
    if (c === 'm') { const x = n(), y = n(); d += `M${x} ${-y}`; }
    else if (c === 'l') { const x = n(), y = n(); d += `L${x} ${-y}`; }
    else if (c === 'q') { const x = n(), y = n(), cx = n(), cy = n(); d += `Q${cx} ${-cy} ${x} ${-y}`; }
    else if (c === 'b') { const x = n(), y = n(), x1 = n(), y1 = n(), x2 = n(), y2 = n(); d += `C${x1} ${-y1} ${x2} ${-y2} ${x} ${-y}`; }
    else if (c === 'z') d += 'Z';
    else throw new Error('unknown op ' + c);
  }
  return d;
};
const out = Object.fromEntries(want.map((name) => { const g = font.glyphs[name]; return [name, { d: toPath(g.o), xMin: g.x_min, xMax: g.x_max, yMin: g.y_min, yMax: g.y_max }]; }));
writeFileSync('libs/react/playback/src/lib/glyphs.ts', `/**
 * A dozen SMuFL music glyphs as SVG paths, in font units with y pointing down (SVG convention).
 * Outlines are Bravura (Steinberg, SIL Open Font License 1.1) as packaged by VexFlow 4.2.5 (MIT);
 * generated by tools/scripts/extract-glyphs.mjs — do not edit by hand. One staff space is
 * FONT_SPACE units, so scale by (spacePx / FONT_SPACE).
 */
export type Glyph = { d: string; xMin: number; xMax: number; yMin: number; yMax: number };
export const FONT_SPACE = 250;
export const GLYPHS: Record<${want.map((w) => `'${w}'`).join(' | ')}, Glyph> = ${JSON.stringify(out, null, 2)};
`);
